name: bowling
description: A simple command-line bowling application.
version: 1.0.1
homepage: https://github.com/castrors/bowling

environment:
  sdk: ">=2.14.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
